services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: .docker/Dockerfile.bun
      target: builder
      secrets:
        - gitlab_npmrc
    volumes:
      - ~/.npmrc:/app/.npmrc
      - .:/app
    environment:
      DB_USERNAME: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: $DB_NAME
      NODE_ENV: development
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    entrypoint: "bun --watch src/index.ts"

secrets:
  gitlab_npmrc:
     file: ~/.npmrc
